SELECT p.PRODUCT_CODE
    , (p.PRICE * SUM(o.SALES_AMOUNT)) AS SALES
  FROM PRODUCT AS p
 INNER JOIN OFFLINE_SALE AS o
    ON p.PRODUCT_ID = o.PRODUCT_ID
 GROUP BY o.PRODUCT_ID
 ORDER BY SALES DESC, PRODUCT_CODE ASC;