SELECT DISTINCT c.CAR_ID
  FROM CAR_RENTAL_COMPANY_CAR AS c
 INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS r
    ON c.CAR_ID = r.CAR_ID
 WHERE c.CAR_TYPE = '세단' 
   AND MONTH(r.START_DATE) = 10
 ORDER BY CAR_ID DESC
;